[[redirects]]
  from = "/github"
  to = "https://github.com/tatjama"
  status = 200
  force = true 

[[redirects]] 
from = "/linkdin" 
to = "https://www.linkedin.com/in/tatjana-markovi%C4%87-919501189/"
status = 200
force = true

[[redirects]]
from = "/cv"
to = "https://optimistic-turing-649781.netlify.app/dowloads/tatjana_markovic_frontend_CV.pdf"
status = 200
force = 

[[redirects]]
from = "/bta" 
to = "https://business-travel-agency-react.vercel.app/"
status = 200

[[redirects]]
from  =  "/eticket" 
to  = "https://tatjama.github.io/e-ticket/"
status = 200

[[redirects]]
from = "/player" 
to = "https://tanja-music.vercel.app/"
status = 200

[[redirects]]
from = "/rock"
to = "https://tatjama.github.io/fem-rock-paper-scissors-master/"
status = 200

[[redirects]]
from = "/fullfun"
to = "https://privatniboravak.com"
status = 200
          
